# Generated by Django 2.2.6 on 2019-12-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191212_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='family',
            field=models.CharField(default=None, max_length=150, verbose_name='family'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=None, max_length=30, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, verbose_name='family'),
        ),
    ]
