# Generated by Django 2.2.5 on 2019-10-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('costomer', models.CharField(db_index=True, max_length=150)),
                ('body', models.TextField(db_index=True)),
                ('date_pud', models.DateTimeField(auto_now_add=True)),
                ('date_tender_end', models.DurationField()),
            ],
        ),
    ]
