# Generated by Django 2.2.6 on 2019-10-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191003_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='clicked',
            field=models.BooleanField(default=False),
        ),
    ]
